config/routes.rb
Rails.application.routes.draw do
  namespace :front do
  get 'websites/new'
  end

  namespace :front do
  get 'websites/create'
  end

  root 'front/tags#index'

  namespace :front do
    resources :tags, only: [:index, :show]
    resources :websites, only: [:new, :create]
  end

  namespace :api do
    resources :websites, only: [:create]
  end

end

app/models/participant.rb
class Participant < ActiveRecord::Base
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ActiveRecord::Base
  has_many :tag_joins
  has_many :websites, through: :tag_joins

  def count_occurences
    self.websites.size
  end
end

app/models/tag_join.rb
# == Schema Information
#
# Table name: tag_joins
#
#  id         :integer          not null, primary key
#  tag_id     :integer
#  website_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class TagJoin < ActiveRecord::Base
  belongs_to :website
  belongs_to :tag
end

app/models/website.rb
# == Schema Information
#
# Table name: websites
#
#  id          :integer          not null, primary key
#  url         :string
#  user_email  :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Website < ActiveRecord::Base
  has_many :tag_joins
  has_many :tags, through: :tag_joins

  accepts_nested_attributes_for :tags
end

app/controllers/api/websites_controller.rb
class Api::WebsitesController < ApplicationController
  protect_from_forgery :except => :create 
  def create

    @website = Website.create(url: wp[:url], description: wp[:description], user_email: wp[:user_email])
    @tag_string = wp[:tags]
    @tags = @tag_string.split(",")
    @tags.each do |tag|
      @tag = Tag.find_or_create_by(name: tag)
      @website.tags << @tag
    end
    
    
    respond_to do |format|
      format.html { render json: @website.to_json }
      format.json { render json: @website.to_json }
    end
  end

  def wp
    params.permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/front/tags_controller.rb
class Front::TagsController < ApplicationController
  def index
    @tags = Tag.all.map { |tag| {text: tag.name, weight: tag.count_occurences, "link": front_tag_path(tag) } }
    

  end

  def show
    @tag = Tag.find(params[:id])
    @websites = @tag.websites
  end
end

app/controllers/front/websites_controller.rb
class Front::WebsitesController < ApplicationController
  def new
    @website = Website.new
    @tag = Tag.new
    
  end

  def create
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name)
    end
end

app/helpers/api/websites_helper.rb
module Api::WebsitesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front/tags_helper.rb
module Front::TagsHelper
end

app/helpers/front/websites_helper.rb
module Front::WebsitesHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/front/tags/index.html.erb
        


        
        <script>
            
            var words = <%= raw @tags.to_json %>;


            // [
            //   {text: "iOS", weight: 13, link: 'http://github.com/mistic100/jQCloud'},
            //   {text: "Ruby", weight: 10.5, link: 'http://www.strangeplanet.fr'},
            //   {text: "Java", weight: 9.4, link: 'http://piwigo.org'},
            //   {text: "Android", weight: 13, link: 'http://github.com/mistic100/jQCloud'},
            //   {text: "Python", weight: 10.5, link: 'http://www.strangeplanet.fr'},
            //   {text: "Rails", weight: 9.4, link: 'http://piwigo.org'},
            //   {text: "PHP", weight: 9.4, link: 'http://piwigo.org'},
            //   {text: "Frontend", weight: 13, link: 'http://github.com/mistic100/jQCloud'},
            //   {text: "Backend", weight: 10.5, link: 'http://www.strangeplanet.fr'},
            //   {text: "Node.js", weight: 13, link: 'http://github.com/mistic100/jQCloud'},
            //   {text: "Angular.js", weight: 10.5, link: 'http://www.strangeplanet.fr'},
            //   {text: "Haskell", weight: 9.4, link: 'http://piwigo.org'},
            // ];

            $(document).ready(function() {
                $('#demo').jQCloud(words, {
                   
                    width: 500,
                    height: 350
                });
                
            });
        
        </script>

        <title>Knowledge Cloud</title>

    </head>


    <body>

        <div class="container">
        <h1>Knowledge Cloud</h1>
        
            <div class="cloud">
                <div id="demo" class="demo"></div>
            </div>
            
        </div>

    </body>

</html>

app/views/front/tags/show.html.erb
<h1>Front::Tags#show</h1>
<p>Find me in app/views/front/tags/show.html.erb</p>


<%= @tag.name %>
<% if @websites %>
  <% @websites.each do |website| %>
  <%= website.url %>
  <%= website.description %>
  <%= website.user_email %>
  <% end %>
  <br>
<% else %>
  No websites for this tag
<% end %>


<p>
<%= link_to "Back to Knowledgecloud", front_tags_path %>
</p>

app/views/front/websites/create.html.erb
<h1>Front::Websites#create</h1>
<p>Find me in app/views/front/websites/create.html.erb</p>

app/views/front/websites/new.html.erb
<h1>Add website</h1>

<% simple_form_for [:front, @website] do |f| %>

<%= f.input :url %>
<%= f.input :description %>
<%= f.input :user_email %>
<%= f.submit "save" %>
`<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knowledgecloud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Participants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Participant', new_participant_path %>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @participant.name %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>